db = new Mongo().getDB('wf-db');

db.createUser({
    user: "wf-admin",
    pwd: "wf-admin",
    roles: [{role: 'readWrite', db: 'wf-db'}],
});

db.createCollection("locations", {capped: false});
db.locations.insertMany([
  {
    "contact": {
      "fax": "250 395-7837",
      "phone": "250 395-7832"
    },
    "services": [
      "Address Change BC",
      "Affordable Child Care Benefit",
      "Industry Training Authority (ITA) Exams",
      "Manufactured Home Searches, Relocation Permits and Initial Registrations",
      "Medical Services Plan/Health Insurance BC",
      "Personal Property (Motor Vehicle) Lien Search",
      "Pesticide Exams",
      "Residential Tenancy Forms and Application Submission",
      "Rural Property Tax Services",
      "Water Rental Payments"
    ],
    "address": {
      "province": "BC",
      "street": "300 BC-97",
      "postal_code": "V0K 2E2",
      "region": "British Columbia",
      "county": "Cariboo",
      "locality": "100 Mile House",
      "label": "300 South Highway 97, 100 Mile House, BC, Canada"
    },
    "locale": "100 Mile House",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-100-mile-house",
    "latitude": 51.644532,
    "longitude": -121.297732
  },
  {
    "contact": {
      "fax": "250 453-9622",
      "phone": "250 453-2412"
    },
    "services": [
      "Address Change BC",
      "Affordable Child Care Benefit",
      "Ambulance Service Fee Payments",
      "Angling Guide Exams",
      "BC Birth Certificate",
      "BC Business Registration",
      "BC Cooperatives",
      "BC Corporations",
      "BC Death Certificate",
      "BC Hydro",
      "BC Marriage Certificate",
      "BC Online (Government Services Online)",
      "BC Services Card",
      "BC Societies",
      "BC Transplant Registration",
      "BC Vital Statistics Services Marriage Licence Issuance in office only;",
      "BCeID (ID for Online Government Services)",
      "Cannabis Worker/Associate Attestation",
      "Claim Rural Home Owner Grant",
      "Commissioner for Taking Affidavits (limited authority)",
      "Community Crisis Fund",
      "Corporate Registry Services",
      "Court Registry Services",
      "Elections BC",
      "Exam Invigilation Services- please call the office to set up an appointment",
      "Fishing (Angling) Licences",
      "Forestry Worker Support Program",
      "Guide Outfitter Exams",
      "Hunting Licence (BC Resident)",
      "Identity Verification",
      "Industry Training Authority (ITA) Exams",
      "Manufactured Home Searches, Relocation Permits and Initial Registrations",
      "Medical Services Plan/Health Insurance BC",
      "Personal Property (Motor Vehicle) Lien Search",
      "Pesticide Exams",
      "Residential Tenancy Forms and Application Submission",
      "Rural Property Tax Services",
      "Water Rental Payments"
    ],
    "address": {
      "province": "BC",
      "street": "318 Railway Ave",
      "postal_code": "V8C 2G2",
      "region": "British Columbia",
      "county": "Thompson-Nicola",
      "locality": "Ashcroft",
      "label": "318 Railway Avenue, Ashcroft, BC, Canada"
    },
    "locale": "Ashcroft",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-ashcroft",
    "latitude": 50.723379,
    "longitude": -121.279436
  },
  {
    "contact": {
      "fax": "250 651-7707",
      "phone": "250 651-7595"
    },
    "services": [
      "Address Change BC",
      "Affordable Child Care Benefit",
      "Ambulance Service Fee Payments",
      "Angling Guide Exams",
      "BC Birth Certificate",
      "BC Business Registration",
      "BC Cooperatives",
      "BC Corporations",
      "BC Death Certificate",
      "BC Hydro",
      "BC Marriage Certificate",
      "BC Online (Government Services Online)",
      "BC Services Card",
      "BC Societies",
      "BC Transplant Registration",
      "BC Vital Statistics Services Marriage Licence Issuance in office only;",
      "BCeID (ID for Online Government Services)",
      "Cannabis Worker/Associate Attestation",
      "Claim Rural Home Owner Grant",
      "Commissioner for Taking Affidavits (limited authority)",
      "Community Crisis Fund",
      "Corporate Registry Services",
      "Court Registry Services",
      "Elections BC",
      "Exam Invigilation Services- please call the office to set up an appointment",
      "Fishing (Angling) Licences",
      "Forestry Worker Support Program",
      "Guide Outfitter Exams",
      "Hunting Licence (BC Resident)",
      "ICBC Driver Licence Services",
      "Identity Verification",
      "Industry Training Authority (ITA) Exams",
      "Manufactured Home Searches, Relocation Permits and Initial Registrations",
      "Medical Services Plan/Health Insurance BC",
      "Personal Property (Motor Vehicle) Lien Search",
      "Pesticide Exams",
      "Residential Tenancy Forms and Application Submission",
      "Rural Property Tax Services",
      "Water Rental Payments"
    ],
    "address": {
      "province": "BC",
      "region": "British Columbia",
      "county": "Stikine",
      "locality": "Atlin-Teslin Indian Cemetery 4",
      "label": "Atlin-Teslin Indian Cemetery 4, BC, Canada"
    },
    "locale": "Atlin",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-atlin",
    "latitude": 59.55889,
    "longitude": -133.690667
  },
  {
    "contact": {
      "fax": "250 799-5450",
      "phone": "250 799-5361"
    },
    "services": [
      "Address Change BC",
      "Affordable Child Care Benefit",
      "Ambulance Service Fee Payments",
      "Angling Guide Exams",
      "BC Birth Certificate",
      "BC Business Registration",
      "BC Cooperatives",
      "BC Corporations",
      "BC Death Certificate",
      "BC Hydro",
      "BC Marriage Certificate",
      "BC Online (Government Services Online)",
      "BC Services Card",
      "BC Societies",
      "BC Transplant Registration",
      "BC Vital Statistics Services Marriage Licence Issuance in office only;",
      "BCeID (ID for Online Government Services)",
      "Cannabis Worker/Associate Attestation",
      "Claim Rural Home Owner Grant",
      "Commissioner for Taking Affidavits (limited authority)",
      "Community Crisis Fund",
      "Corporate Registry Services",
      "Court Registry Services",
      "Elections BC",
      "Exam Invigilation Services- please call the office to set up an appointment",
      "Fishing (Angling) Licences",
      "Forestry Worker Support Program",
      "Guide Outfitter Exams",
      "Hunting Licence (BC Resident)",
      "ICBC Driver Licence Services",
      "Identity Verification",
      "Industry Training Authority (ITA) Exams",
      "Manufactured Home Searches, Relocation Permits and Initial Registrations",
      "Medical Services Plan/Health Insurance BC",
      "Personal Property (Motor Vehicle) Lien Search",
      "Pesticide Exams",
      "Residential Tenancy Forms and Application Submission",
      "Rural Property Tax Services",
      "Water Rental Payments"
    ],
    "address": {
      "province": "BC",
      "street": "636 Cliff St",
      "postal_code": "V0T 1C0",
      "region": "British Columbia",
      "county": "Central Coast",
      "locality": "Bella Coola 1",
      "label": "Bella Coola 1, BC, Canada"
    },
    "locale": "Bella Coola",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-bella-coola",
    "latitude": 52.38034,
    "longitude": -126.722219
  },
  {
    "contact": {
      "fax": "",
      "phone": "1 800 663-7867"
    },
    "services": [
      "BC Services Card",
      "BCeID (ID for Online Government Services)",
      "Hazardous Waste License to Transport Applications (new and renewal).Email your application package to: applications.sbc@gov.bc.ca",
      "Identity Verification",
      "Pesticide License Applications (new and renewals). Email your application package to: applications.sbc@gov.bc.ca"
    ],
    "address": {
      "province": "BC",
      "region": "British Columbia",
      "county": "Greater Vancouver",
      "locality": "Burnaby",
      "label": "Burnaby, BC, Canada"
    },
    "locale": "Burnaby",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-burnaby",
    "latitude": 49.248223,
    "longitude": -122.966319
  },
  {
    "contact": {
      "fax": "250 692-2530",
      "phone": "250 692-2528"
    },
    "services": [
      "Address Change BC",
      "Affordable Child Care Benefit",
      "Ambulance Service Fee Payments",
      "Angling Guide Exams",
      "BC Birth Certificate",
      "BC Business Registration",
      "BC Cooperatives",
      "BC Corporations",
      "BC Death Certificate",
      "BC Hydro",
      "BC Marriage Certificate",
      "BC Online (Government Services Online)",
      "BC Services Card",
      "BC Societies",
      "BC Transplant Registration",
      "BC Vital Statistics Services Marriage Licence Issuance in office only;",
      "BCeID (ID for Online Government Services)",
      "Cannabis Worker/Associate Attestation",
      "Claim Rural Home Owner Grant",
      "Commissioner for Taking Affidavits (limited authority)",
      "Community Crisis Fund",
      "Corporate Registry Services",
      "Court Registry Services",
      "Elections BC",
      "Exam Invigilation Services- please call the office to set up an appointment",
      "Fishing (Angling) Licences",
      "Forestry Worker Support Program",
      "Guide Outfitter Exams",
      "Hunting Licence (BC Resident)",
      "Identity Verification",
      "Industry Training Authority (ITA) Exams",
      "Manufactured Home Searches, Relocation Permits and Initial Registrations",
      "Medical Services Plan/Health Insurance BC",
      "Personal Property (Motor Vehicle) Lien Search",
      "Pesticide Exams",
      "Residential Tenancy Forms and Application Submission",
      "Rural Property Tax Services",
      "Water Rental Payments"
    ],
    "address": {
      "province": "BC",
      "street": "161 BC-16",
      "postal_code": "V0J 1E0",
      "region": "British Columbia",
      "county": "Bulkley-Nechako",
      "locality": "Burns Lake",
      "label": "161 Highway 16, Burns Lake, BC, Canada"
    },
    "locale": "Burns Lake",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-burns-lake",
    "latitude": 54.224986,
    "longitude": -125.755558
  },
  {
    "contact": {
      "fax": "250 286-7573",
      "phone": "250 286-7555"
    },
    "services": [
      "Address Change BC",
      "Affordable Child Care Benefit",
      "Ambulance Service Fee Payments",
      "Angling Guide Exams",
      "BC Birth Certificate",
      "BC Business Registration",
      "BC Cooperatives",
      "BC Corporations",
      "BC Death Certificate",
      "BC Hydro",
      "BC Marriage Certificate",
      "BC Online (Government Services Online)",
      "BC Services Card",
      "BC Societies",
      "BC Transplant Registration",
      "BC Vital Statistics Services Marriage Licence Issuance in office only;",
      "BCeID (ID for Online Government Services)",
      "Cannabis Worker/Associate Attestation",
      "Claim Rural Home Owner Grant",
      "Commissioner for Taking Affidavits (limited authority)",
      "Community Crisis Fund",
      "Corporate Registry Services",
      "Court Registry Services",
      "Elections BC",
      "Exam Invigilation Services- please call the office to set up an appointment",
      "Fishing (Angling) Licences",
      "Forestry Worker Support Program",
      "Guide Outfitter Exams",
      "Hunting Licence (BC Resident)",
      "ICBC Driver Licence Services",
      "Identity Verification",
      "Industry Training Authority (ITA) Exams",
      "Manufactured Home Searches, Relocation Permits and Initial Registrations",
      "Medical Services Plan/Health Insurance BC",
      "Personal Property (Motor Vehicle) Lien Search",
      "Pesticide Exams",
      "Residential Tenancy Forms and Application Submission",
      "Rural Property Tax Services",
      "Water Rental Payments"
    ],
    "address": {
      "province": "BC",
      "postal_code": "V9W 5P7",
      "region": "British Columbia",
      "county": "Strathcona",
      "locality": "Campbell River",
      "label": "1180 Ironwood St, Campbell River, BC, Canada"
    },
    "locale": "Campbell River",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-campbell-river",
    "latitude": 50.026703,
    "longitude": -125.255394
  },
  {
    "contact": {
      "fax": "250 788-3802",
      "phone": "250 788-2239"
    },
    "services": [
      "Address Change BC",
      "Affordable Child Care Benefit",
      "Ambulance Service Fee Payments",
      "Angling Guide Exams",
      "BC Birth Certificate",
      "BC Business Registration",
      "BC Cooperatives",
      "BC Corporations",
      "BC Death Certificate",
      "BC Hydro",
      "BC Marriage Certificate",
      "BC Online (Government Services Online)",
      "BC Services Card",
      "BC Societies",
      "BC Transplant Registration",
      "BC Vital Statistics Services Marriage Licence Issuance in office only;",
      "BCeID (ID for Online Government Services)",
      "Cannabis Worker/Associate Attestation",
      "Claim Rural Home Owner Grant",
      "Commissioner for Taking Affidavits (limited authority)",
      "Community Crisis Fund",
      "Corporate Registry Services",
      "Court Registry Services",
      "Elections BC",
      "Exam Invigilation Services- please call the office to set up an appointment",
      "Fishing (Angling) Licences",
      "Forestry Worker Support Program",
      "Guide Outfitter Exams",
      "Hunting Licence (BC Resident)",
      "ICBC Driver Licence Services",
      "Identity Verification",
      "Industry Training Authority (ITA) Exams",
      "Manufactured Home Searches, Relocation Permits and Initial Registrations",
      "Medical Services Plan/Health Insurance BC",
      "Personal Property (Motor Vehicle) Lien Search",
      "Pesticide Exams",
      "Residential Tenancy Forms and Application Submission",
      "Rural Property Tax Services",
      "Water Rental Payments"
    ],
    "address": {
      "province": "BC",
      "street": "4744 52 St NW",
      "postal_code": "V0C 1J0",
      "region": "British Columbia",
      "county": "Peace River",
      "locality": "Chetwynd",
      "label": "4744 52 St NW, Chetwynd, BC, Canada"
    },
    "locale": "Chetwynd",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-chetwynd",
    "latitude": 55.69809,
    "longitude": -121.633272
  },
  {
    "contact": {
      "fax": "604 795-8408",
      "phone": "604 795-8415"
    },
    "services": [
      "Address Change BC",
      "Affordable Child Care Benefit",
      "Ambulance Service Fee Payments",
      "Angling Guide Exams",
      "BC Birth Certificate",
      "BC Business Registration",
      "BC Cooperatives",
      "BC Corporations",
      "BC Death Certificate",
      "BC Hydro",
      "BC Marriage Certificate",
      "BC Online (Government Services Online)",
      "BC Services Card",
      "BC Societies",
      "BC Transplant Registration",
      "BC Vital Statistics Services Marriage Licence Issuance in office only;",
      "BCeID (ID for Online Government Services)",
      "Cannabis Worker/Associate Attestation",
      "Claim Rural Home Owner Grant",
      "Commissioner for Taking Affidavits (limited authority)",
      "Community Crisis Fund",
      "Corporate Registry Services",
      "Court Registry Services",
      "Elections BC",
      "Exam Invigilation Services- please call the office to set up an appointment",
      "Fishing (Angling) Licences",
      "Forestry Worker Support Program",
      "Guide Outfitter Exams",
      "Hunting Licence (BC Resident)",
      "ICBC Driver Licence Services",
      "Identity Verification",
      "Industry Training Authority (ITA) Exams",
      "Manufactured Home Searches, Relocation Permits and Initial Registrations",
      "Medical Services Plan/Health Insurance BC",
      "Personal Property (Motor Vehicle) Lien Search",
      "Pesticide Exams",
      "Residential Tenancy Forms and Application Submission",
      "Rural Property Tax Services",
      "Water Rental Payments"
    ],
    "address": {
      "province": "BC",
      "postal_code": "V2R 3Z8"
    },
    "locale": "Chilliwack",
    "website": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services/servicebc/service-bc-location-chilliwack"
  },
]);
